# Generated by Django 4.1.2 on 2022-10-11 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_author_book_bookintance_genre_delete_mymodelname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='date_of_bitrh',
            new_name='date_of_birth',
        ),
    ]
